#!/usr/bin/env bash
# Fetch BigMoeOnEdge + llama.cpp and build a static lib for device iOS (arm64).
# Writes ios/Flutter/bmoe.xcconfig so Runner links it on the next Xcode/Flutter build.
#
# Usage (from repo root):
#   ./ios/scripts/fetch_and_build_bmoe.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
PIN_FILE="$ROOT/third_party/bigmoe.pin"
VENDOR="$ROOT/third_party/bigmoe"
BUILD="$ROOT/ios/build/bmoe"
XCCONFIG="$ROOT/ios/Flutter/bmoe.xcconfig"

BMOE_REPO="https://github.com/Helldez/BigMoeOnEdge.git"
BMOE_REF="$(tr -d '[:space:]' < "$PIN_FILE" 2>/dev/null || true)"
if [[ -z "$BMOE_REF" ]]; then
  BMOE_REF="main"
fi

if ! command -v cmake >/dev/null; then
  echo "cmake is required (brew install cmake)" >&2
  exit 1
fi

mkdir -p "$ROOT/third_party"
if [[ ! -d "$VENDOR/.git" ]]; then
  echo "Cloning BigMoeOnEdge ($BMOE_REF) into third_party/bigmoe …"
  git clone --recurse-submodules --depth 1 --branch "$BMOE_REF" "$BMOE_REPO" "$VENDOR" \
    || git clone --recurse-submodules --depth 1 "$BMOE_REPO" "$VENDOR"
else
  echo "Updating existing third_party/bigmoe …"
  git -C "$VENDOR" fetch --depth 1 origin "$BMOE_REF" || git -C "$VENDOR" fetch --depth 1 origin
  git -C "$VENDOR" checkout --detach FETCH_HEAD || true
  git -C "$VENDOR" submodule update --init --recursive --depth 1
fi

if [[ ! -f "$VENDOR/third_party/llama.cpp/CMakeLists.txt" ]]; then
  echo "llama.cpp submodule missing — running submodule update" >&2
  git -C "$VENDOR" submodule update --init --recursive
fi

# checkout --detach + submodule update wipe local llama.cpp edits. Re-apply Mini's
# iOS mmap chunking (single 18 GiB mmap ENOMEMs on iPhone).
PATCH="$ROOT/ios/patches/llama-mmap-ios-chunks.patch"
LLAMA_SRC="$VENDOR/third_party/llama.cpp"
if [[ -f "$PATCH" && -f "$LLAMA_SRC/src/llama-mmap.cpp" ]]; then
  if grep -q 'iOS mapped' "$LLAMA_SRC/src/llama-mmap.cpp"; then
    echo "iOS mmap chunk patch already present"
  else
    echo "Applying iOS mmap chunk patch to llama.cpp"
    git -C "$LLAMA_SRC" apply "$PATCH"
  fi
fi

SDK="$(xcrun --sdk iphoneos --show-sdk-path)"
# llama.cpp defaults BUILD_SHARED_LIBS=ON; iOS needs archives we can force-load
# into Runner (dylibs are not embeddable from this CMake graph).
# Empty CMAKE_SYSTEM_PROCESSOR + iOS try_compile drops DOTPROD/I8MM; force them
# for A14+ phones (this engine is aimed at 16 Pro class devices).
ARM_IOS_FLAGS="-march=armv8.4-a+dotprod+fp16+i8mm"
CMAKE_IOS_ARGS=(
  -DCMAKE_SYSTEM_NAME=iOS
  -DCMAKE_SYSTEM_PROCESSOR=arm64
  -DCMAKE_OSX_ARCHITECTURES=arm64
  -DCMAKE_OSX_DEPLOYMENT_TARGET=16.4
  -DCMAKE_OSX_SYSROOT="$SDK"
  -DCMAKE_BUILD_TYPE=Release
  -DCMAKE_POSITION_INDEPENDENT_CODE=ON
  -DCMAKE_C_FLAGS="$ARM_IOS_FLAGS"
  -DCMAKE_CXX_FLAGS="$ARM_IOS_FLAGS"
  -DBMOE_BUILD_TESTS=OFF
  -DBMOE_BUILD_CLI=OFF
  -DBMOE_BUILD_TOOLS=OFF
  -DBUILD_SHARED_LIBS=OFF
  -DGGML_STATIC=ON
  -DGGML_METAL=OFF
  -DGGML_NATIVE=OFF
  -DGGML_OPENMP=OFF
  -DGGML_CCACHE=OFF
  -DLLAMA_BUILD_TESTS=OFF
  -DLLAMA_BUILD_EXAMPLES=OFF
  -DLLAMA_BUILD_SERVER=OFF
)

# Shared leftovers from an older configure poison the ninja graph.
if grep -q 'BUILD_SHARED_LIBS:BOOL=ON' "$BUILD/CMakeCache.txt" 2>/dev/null; then
  echo "Clearing $BUILD (was a shared-library configure)"
  rm -rf "$BUILD"
fi
mkdir -p "$BUILD"
cmake -S "$VENDOR" -B "$BUILD" -G Ninja "${CMAKE_IOS_ARGS[@]}"

if ! command -v ninja >/dev/null; then
  echo "ninja not found, falling back to Unix Makefiles"
  cmake -S "$VENDOR" -B "$BUILD" -G "Unix Makefiles" "${CMAKE_IOS_ARGS[@]}"
  cmake --build "$BUILD" --target bmoe_core --config Release -j"$(sysctl -n hw.ncpu)"
else
  cmake --build "$BUILD" --target bmoe_core --config Release
fi

LIBDIR="$BUILD"
# Ninja/Make may nest the archive.
LIB="$(find "$BUILD" -name 'libbmoe_core.a' | head -n 1)"
LLAMA="$(find "$BUILD" -name 'libllama.a' | head -n 1)"
GGML="$(find "$BUILD" -name 'libggml.a' | head -n 1 || true)"
if [[ -z "$LIB" || -z "$LLAMA" ]]; then
  echo "Build finished but libbmoe_core.a / libllama.a not found under $BUILD" >&2
  find "$BUILD" -name '*.a' | head
  exit 1
fi

# Collect sibling static libs llama.cpp emits.
EXTRA_LIBS=()
while IFS= read -r a; do
  EXTRA_LIBS+=("\"$a\"")
done < <(find "$BUILD" -name '*.a' | sort)

LDFLAGS=""
for a in "${EXTRA_LIBS[@]}"; do
  LDFLAGS+=" -force_load $a"
done

cat > "$XCCONFIG" <<EOF
// Generated by ios/scripts/fetch_and_build_bmoe.sh — do not commit.
// Device-only: these archives are iphoneos arm64 and cannot link into the Simulator.
HEADER_SEARCH_PATHS[sdk=iphoneos*] = \$(inherited) "$VENDOR/core/include" "$VENDOR/third_party/llama.cpp/include" "$VENDOR/third_party/llama.cpp/ggml/include"
LIBRARY_SEARCH_PATHS[sdk=iphoneos*] = \$(inherited) "$LIBDIR"
OTHER_LDFLAGS[sdk=iphoneos*] = \$(inherited)$LDFLAGS -lc++ -framework Accelerate -framework Foundation -framework Security
GCC_PREPROCESSOR_DEFINITIONS[sdk=iphoneos*] = \$(inherited) LM_MINI_HAS_BMOE=1
EOF

echo "Wrote $XCCONFIG"
echo "Next: flutter run -d <iphone>  (physical device, not Simulator)"
