/// Whisper multilingual language codes (OpenAI tokenizer, 99 languages).
class WhisperLanguage {
  final String code;
  final String name;

  const WhisperLanguage(this.code, this.name);

  static const auto = WhisperLanguage('auto', 'Auto-detect');

  static const List<WhisperLanguage> all = [
    auto,
    WhisperLanguage('af', 'Afrikaans'),
    WhisperLanguage('sq', 'Albanian'),
    WhisperLanguage('am', 'Amharic'),
    WhisperLanguage('ar', 'Arabic'),
    WhisperLanguage('hy', 'Armenian'),
    WhisperLanguage('as', 'Assamese'),
    WhisperLanguage('az', 'Azerbaijani'),
    WhisperLanguage('ba', 'Bashkir'),
    WhisperLanguage('eu', 'Basque'),
    WhisperLanguage('be', 'Belarusian'),
    WhisperLanguage('bn', 'Bengali'),
    WhisperLanguage('bs', 'Bosnian'),
    WhisperLanguage('br', 'Breton'),
    WhisperLanguage('bg', 'Bulgarian'),
    WhisperLanguage('my', 'Burmese'),
    WhisperLanguage('ca', 'Catalan'),
    WhisperLanguage('yue', 'Cantonese'),
    WhisperLanguage('zh', 'Chinese'),
    WhisperLanguage('hr', 'Croatian'),
    WhisperLanguage('cs', 'Czech'),
    WhisperLanguage('da', 'Danish'),
    WhisperLanguage('nl', 'Dutch'),
    WhisperLanguage('en', 'English'),
    WhisperLanguage('et', 'Estonian'),
    WhisperLanguage('fo', 'Faroese'),
    WhisperLanguage('fi', 'Finnish'),
    WhisperLanguage('fr', 'French'),
    WhisperLanguage('gl', 'Galician'),
    WhisperLanguage('ka', 'Georgian'),
    WhisperLanguage('de', 'German'),
    WhisperLanguage('el', 'Greek'),
    WhisperLanguage('gu', 'Gujarati'),
    WhisperLanguage('ht', 'Haitian Creole'),
    WhisperLanguage('ha', 'Hausa'),
    WhisperLanguage('haw', 'Hawaiian'),
    WhisperLanguage('he', 'Hebrew'),
    WhisperLanguage('hi', 'Hindi'),
    WhisperLanguage('hu', 'Hungarian'),
    WhisperLanguage('is', 'Icelandic'),
    WhisperLanguage('id', 'Indonesian'),
    WhisperLanguage('it', 'Italian'),
    WhisperLanguage('ja', 'Japanese'),
    WhisperLanguage('jw', 'Javanese'),
    WhisperLanguage('kn', 'Kannada'),
    WhisperLanguage('kk', 'Kazakh'),
    WhisperLanguage('km', 'Khmer'),
    WhisperLanguage('ko', 'Korean'),
    WhisperLanguage('lo', 'Lao'),
    WhisperLanguage('la', 'Latin'),
    WhisperLanguage('lv', 'Latvian'),
    WhisperLanguage('ln', 'Lingala'),
    WhisperLanguage('lt', 'Lithuanian'),
    WhisperLanguage('lb', 'Luxembourgish'),
    WhisperLanguage('mk', 'Macedonian'),
    WhisperLanguage('mg', 'Malagasy'),
    WhisperLanguage('ms', 'Malay'),
    WhisperLanguage('ml', 'Malayalam'),
    WhisperLanguage('mt', 'Maltese'),
    WhisperLanguage('mi', 'Maori'),
    WhisperLanguage('mr', 'Marathi'),
    WhisperLanguage('mn', 'Mongolian'),
    WhisperLanguage('ne', 'Nepali'),
    WhisperLanguage('no', 'Norwegian'),
    WhisperLanguage('nn', 'Nynorsk'),
    WhisperLanguage('oc', 'Occitan'),
    WhisperLanguage('ps', 'Pashto'),
    WhisperLanguage('fa', 'Persian'),
    WhisperLanguage('pl', 'Polish'),
    WhisperLanguage('pt', 'Portuguese'),
    WhisperLanguage('pa', 'Punjabi'),
    WhisperLanguage('ro', 'Romanian'),
    WhisperLanguage('ru', 'Russian'),
    WhisperLanguage('sa', 'Sanskrit'),
    WhisperLanguage('sr', 'Serbian'),
    WhisperLanguage('sn', 'Shona'),
    WhisperLanguage('sd', 'Sindhi'),
    WhisperLanguage('si', 'Sinhala'),
    WhisperLanguage('sk', 'Slovak'),
    WhisperLanguage('sl', 'Slovenian'),
    WhisperLanguage('so', 'Somali'),
    WhisperLanguage('es', 'Spanish'),
    WhisperLanguage('su', 'Sundanese'),
    WhisperLanguage('sw', 'Swahili'),
    WhisperLanguage('sv', 'Swedish'),
    WhisperLanguage('tl', 'Tagalog'),
    WhisperLanguage('tg', 'Tajik'),
    WhisperLanguage('ta', 'Tamil'),
    WhisperLanguage('tt', 'Tatar'),
    WhisperLanguage('te', 'Telugu'),
    WhisperLanguage('th', 'Thai'),
    WhisperLanguage('bo', 'Tibetan'),
    WhisperLanguage('tr', 'Turkish'),
    WhisperLanguage('tk', 'Turkmen'),
    WhisperLanguage('uk', 'Ukrainian'),
    WhisperLanguage('ur', 'Urdu'),
    WhisperLanguage('uz', 'Uzbek'),
    WhisperLanguage('vi', 'Vietnamese'),
    WhisperLanguage('cy', 'Welsh'),
    WhisperLanguage('yi', 'Yiddish'),
    WhisperLanguage('yo', 'Yoruba'),
  ];

  static WhisperLanguage? findByCode(String code) {
    for (final lang in all) {
      if (lang.code == code) return lang;
    }
    return null;
  }

  /// Maps UI `auto` to empty string for sherpa-onnx (language detection).
  static String sherpaLanguageCode(String code) =>
      code == 'auto' ? '' : code;
}
